// <auto-generated />
using Fiap.ProjetoRelacionamento.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fiap.ProjetoRelacionamento.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190911114744_Time")]
    partial class Time
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fiap.ProjetoRelacionamento.Models.Time", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Esporte");

                    b.Property<bool>("Mascote");

                    b.Property<string>("Nome");

                    b.HasKey("Codigo");

                    b.ToTable("Times");
                });
#pragma warning restore 612, 618
        }
    }
}
