// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _04_Fiap.Web.Asp.net.Persistencia;

namespace _04_Fiap.Web.Asp.net.Migrations
{
    [DbContext(typeof(LocadoraContext))]
    [Migration("20190828142655_Pao")]
    partial class Pao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_04_Fiap.Web.Asp.net.Models.Veiculo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cd_veiculo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataFabricacao")
                        .HasColumnName("dt_fabricacao");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnName("ds_modelo")
                        .HasMaxLength(100);

                    b.Property<float>("Peso")
                        .HasColumnName("vl_Peso");

                    b.Property<int>("TipoCombustivel")
                        .HasColumnName("tp_combustivel");

                    b.HasKey("Codigo");

                    b.ToTable("Veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
